configuration:
  outputFile:
    absolutePath: C:\dev-workspace\poc-keycloak\
    filePath: scripts\rs256-secret.yaml
  driverPath: src/main/resources/drivers/chromedriver.exe
  login:
    uri: http://localhost:8091/auth/
    username: admin
    password: admin
  realm:
    name: poc-management
    tokenTtlMinutes: 30
  role:
    name: partners
  client:
    name: front-poc-app
    redirectUriFields: '*'
  delay:
    basic: 1000
    openBrowser: 1750